### PR TITLE
EP-50869: hiding vulnerabilities tab and vulnerability report in history section in tool repo.

### PR DESCRIPTION
**Pull request by ns-svemu**
Earlier with tool repo we are showing vulnerabilities col and report section
Screenshot 2024-09-12 at 5 58 48 PM
Screenshot 2024-09-12 at 5 59 03 PM

After this code we are hiding vulnerabilities for tool-repo
Screenshot 2024-09-12 at 6 09 17 PM

Screenshot 2024-09-12 at 6 09 25 PM

### CODE REVIEW

**Comment by ns-kmore** [comment]
@ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it. 

Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.

**Comment by ns-svemu** [comment]
> @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> 
> Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.

Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.

**Comment by ns-kmore** [comment]
> > @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> > Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.
> 
> Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.

**Comment by ns-kmore** [comment]
> > > @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> > > Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.
> > 
> > 
> > Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.

@ns-svemu I think, we dont need to make any changes in ep-pokeball. The changes I suggested should be made in these riot files only where we make fetch calls and parse the report data. IMO we could avoid that compute.

> > > @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> > > Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.
> > 
> > 
> > Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.

**Comment by ns-svemu** [comment]
> > > > @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> > > > Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.
> > > 
> > > 
> > > Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.
> 
> @ns-svemu I think, we dont need to make any changes in ep-pokeball. The changes I suggested should be made in these riot files only where we make fetch calls and parse the report data. IMO we could avoid that compute.
> 
> > > > @ns-svemu These changes are UI only. **IF** report presentation for tools category images is not needed then report fetching + parsing should not also happen. Please add necessary conditions in the backend where we pull in the report data and process it.
> > > > Also, as we work on the same docker registry ui codebase , please do add me to the reviewers list as I do, so we are aware of each other's changes.
> > > 
> > > 
> > > Sure @ns-kmore. I will handle it in ep-pokeball-backend code. Thank you.
@ns-kmore - i have added the necessary condition to it.

**Review by ns-ggeorgiev — APPROVED** [review]

**Pull request merged**
